#!/usr/bin/env python3
"""Regenerate all test fixtures derived from '[[Test Article]] 0'.

Writes:
  tests/fixtures/yaml/test_article_0_nodes.yaml
  tests/fixtures/yaml/test_article_0_vertices.yaml
  tests/fixtures/markdown/test_article_0_expected.md

Run from the project root with the venv active:
  python scripts/regen_article0_fixtures.py
"""

import pathlib
import sys
import tempfile

import yaml

from guffin.filenames import shell_safe_filename
from guffin.graph import VertexTree, vertex_adapter
from guffin.logging_config import configure_logging
from guffin.md_rendering import render
from guffin.roam_local_api import ApiEndpoint
from guffin.roam_node import RoamNode
from guffin.roam_node_fetch import FetchRoamNodes
from guffin.roam_node_fetch_result import NodeFetchAnchor, NodeFetchSpec
from guffin.roam_transcribe import transcribe
from guffin.roam_tree import NodeTree

configure_logging()

PAGE_TITLE = "[[Test Article]] 0"
FIXTURES_YAML = pathlib.Path("tests/fixtures/yaml")
FIXTURES_MD = pathlib.Path("tests/fixtures/markdown")

ENDPOINT = ApiEndpoint.from_parts(
    local_api_port=3333,
    graph_name="SCFH",
    bearer_token="roam-graph-local-token-OR3s0AcJn5rwxPJ6MYaqnIyjNi7ai",
)

_TRANSIENT_FIELDS = {"open", "sidebar", "lookup", "seen_by"}


def _stub_node_dict(node: RoamNode) -> dict[str, object]:
    """Serialise *node* with transient fields stubbed/omitted for fixture storage."""
    d: dict[str, object] = node.model_dump(mode="json")
    d["time"] = 0
    d["user"] = {"id": 0}
    for key in _TRANSIENT_FIELDS:
        d.pop(key, None)
    return d


# ---------------------------------------------------------------------------
# 1. Fetch nodes
# ---------------------------------------------------------------------------
print(f"Fetching '{PAGE_TITLE}' from live API …")
result = FetchRoamNodes.fetch_by_page_title(
    fetch_spec=NodeFetchSpec(anchor=NodeFetchAnchor(qualifier=PAGE_TITLE), include_refs=False),
    api_endpoint=ENDPOINT,
)
nodes: list[RoamNode] = list(result.network)
print(f"  fetched {len(nodes)} node(s)")

# ---------------------------------------------------------------------------
# 2. Write nodes YAML
# ---------------------------------------------------------------------------
nodes_path = FIXTURES_YAML / "test_article_0_nodes.yaml"
node_dicts = [_stub_node_dict(n) for n in nodes]
nodes_header = (
    "# YAML fixture for the '[[Test Article]] 0' NodeNetwork.\n"
    "# Regenerated by scripts/regen_article0_fixtures.py.\n"
    "# Serialised with model_dump(mode='json') and yaml.dump(\n"
    "#   default_flow_style=False, allow_unicode=True, sort_keys=False).\n"
    "#\n"
    "# Transient fields (time, user, open, sidebar, lookup, seen_by) are excluded\n"
    "# from live-test comparisons and are set to stub values here (time: 0,\n"
    "# user: {id: 0}); the nullable ones (open, sidebar, lookup, seen_by) are\n"
    "# omitted entirely so they default to None on model_validate.\n"
)
nodes_path.write_text(
    nodes_header + yaml.dump(node_dicts, default_flow_style=False, allow_unicode=True, sort_keys=False),
    encoding="utf-8",
)
print(f"  wrote {nodes_path}")

# ---------------------------------------------------------------------------
# 3. Build NodeTree and transcribe to VertexTree
# ---------------------------------------------------------------------------
root_node = next(n for n in nodes if n.title == PAGE_TITLE)
node_tree = NodeTree.build(super_network=nodes, root_node=root_node)
vertex_tree: VertexTree = transcribe(node_tree)
print(f"  transcribed {len(vertex_tree.vertices)} vertex/vertices")

# ---------------------------------------------------------------------------
# 4. Write vertices YAML
# ---------------------------------------------------------------------------
vertices_path = FIXTURES_YAML / "test_article_0_vertices.yaml"
vertex_dicts = [vertex_adapter.dump_python(v, mode="json", exclude_none=True) for v in vertex_tree.vertices]
vertices_header = (
    "# YAML fixture for the '[[Test Article]] 0' VertexTree.\n"
    "# Regenerated by scripts/regen_article0_fixtures.py.\n"
    "# Serialised with model_dump(mode='json', exclude_none=True) and yaml.dump(\n"
    "#   default_flow_style=False, allow_unicode=True, sort_keys=False).\n"
)
vertices_path.write_text(
    vertices_header + yaml.dump(vertex_dicts, default_flow_style=False, allow_unicode=True, sort_keys=False),
    encoding="utf-8",
)
print(f"  wrote {vertices_path}")

# ---------------------------------------------------------------------------
# 5. Render and write expected markdown
# ---------------------------------------------------------------------------
md_path = FIXTURES_MD / "test_article_0_expected.md"
with tempfile.TemporaryDirectory() as tmp_dir:
    render(
        vertex_tree,
        filename_stem=PAGE_TITLE,
        output_dir=pathlib.Path(tmp_dir),
        api_endpoint=ENDPOINT,
        bundle=False,
    )
    rendered = (pathlib.Path(tmp_dir) / f"{shell_safe_filename(PAGE_TITLE)}.md").read_text(encoding="utf-8")
md_path.write_text(rendered, encoding="utf-8")
print(f"  wrote {md_path}")

print("Done.")
sys.exit(0)
